[package]
name = "lab-11"
version = "0.1.0"
authors = ["Matt Hayes <matt@mysterycommand.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.43"

[dependencies.web-sys]
version = "0.3.20"
features = [
  'CanvasRenderingContext2d',
]
